/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CategoryUpdateManyWithoutUsersInput } from "./CategoryUpdateManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { CompanyUpdateManyWithoutUsersInput } from "./CompanyUpdateManyWithoutUsersInput";
import { FactureUpdateManyWithoutUsersInput } from "./FactureUpdateManyWithoutUsersInput";
import { ProductUpdateManyWithoutUsersInput } from "./ProductUpdateManyWithoutUsersInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CategoryUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CategoryUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CategoryUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  category?: CategoryUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => CompanyUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => CompanyUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => CompanyUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  company?: CompanyUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => FactureUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => FactureUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => FactureUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  factures?: FactureUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: () => ProductUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ProductUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ProductUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  product?: ProductUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
