/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FactureService } from "../facture.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FactureCreateInput } from "./FactureCreateInput";
import { Facture } from "./Facture";
import { FactureFindManyArgs } from "./FactureFindManyArgs";
import { FactureWhereUniqueInput } from "./FactureWhereUniqueInput";
import { FactureUpdateInput } from "./FactureUpdateInput";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FactureControllerBase {
  constructor(
    protected readonly service: FactureService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Facture })
  @nestAccessControl.UseRoles({
    resource: "Facture",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFacture(
    @common.Body() data: FactureCreateInput
  ): Promise<Facture> {
    return await this.service.createFacture({
      data: {
        ...data,

        companies: data.companies
          ? {
              connect: data.companies,
            }
          : undefined,

        users: data.users
          ? {
              connect: data.users,
            }
          : undefined,
      },
      select: {
        companies: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        discount: true,
        id: true,
        quantity: true,
        totalPrice: true,
        tva: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Facture] })
  @ApiNestedQuery(FactureFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Facture",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async factures(@common.Req() request: Request): Promise<Facture[]> {
    const args = plainToClass(FactureFindManyArgs, request.query);
    return this.service.factures({
      ...args,
      select: {
        companies: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        discount: true,
        id: true,
        quantity: true,
        totalPrice: true,
        tva: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Facture })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Facture",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async facture(
    @common.Param() params: FactureWhereUniqueInput
  ): Promise<Facture | null> {
    const result = await this.service.facture({
      where: params,
      select: {
        companies: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        discount: true,
        id: true,
        quantity: true,
        totalPrice: true,
        tva: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Facture })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Facture",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFacture(
    @common.Param() params: FactureWhereUniqueInput,
    @common.Body() data: FactureUpdateInput
  ): Promise<Facture | null> {
    try {
      return await this.service.updateFacture({
        where: params,
        data: {
          ...data,

          companies: data.companies
            ? {
                connect: data.companies,
              }
            : undefined,

          users: data.users
            ? {
                connect: data.users,
              }
            : undefined,
        },
        select: {
          companies: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          discount: true,
          id: true,
          quantity: true,
          totalPrice: true,
          tva: true,
          updatedAt: true,

          users: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Facture })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Facture",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFacture(
    @common.Param() params: FactureWhereUniqueInput
  ): Promise<Facture | null> {
    try {
      return await this.service.deleteFacture({
        where: params,
        select: {
          companies: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          discount: true,
          id: true,
          quantity: true,
          totalPrice: true,
          tva: true,
          updatedAt: true,

          users: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/product")
  @ApiNestedQuery(ProductFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Product",
    action: "read",
    possession: "any",
  })
  async findProduct(
    @common.Req() request: Request,
    @common.Param() params: FactureWhereUniqueInput
  ): Promise<Product[]> {
    const query = plainToClass(ProductFindManyArgs, request.query);
    const results = await this.service.findProduct(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        itemPrice: true,
        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/product")
  @nestAccessControl.UseRoles({
    resource: "Facture",
    action: "update",
    possession: "any",
  })
  async connectProduct(
    @common.Param() params: FactureWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      product: {
        connect: body,
      },
    };
    await this.service.updateFacture({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/product")
  @nestAccessControl.UseRoles({
    resource: "Facture",
    action: "update",
    possession: "any",
  })
  async updateProduct(
    @common.Param() params: FactureWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      product: {
        set: body,
      },
    };
    await this.service.updateFacture({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/product")
  @nestAccessControl.UseRoles({
    resource: "Facture",
    action: "update",
    possession: "any",
  })
  async disconnectProduct(
    @common.Param() params: FactureWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      product: {
        disconnect: body,
      },
    };
    await this.service.updateFacture({
      where: params,
      data,
      select: { id: true },
    });
  }
}
