/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CategoryUpdateManyWithoutProductsInput } from "./CategoryUpdateManyWithoutProductsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  IsNumber,
} from "class-validator";
import { Type } from "class-transformer";
import { FactureUpdateManyWithoutProductsInput } from "./FactureUpdateManyWithoutProductsInput";
import { UserUpdateManyWithoutProductsInput } from "./UserUpdateManyWithoutProductsInput";

@InputType()
class ProductUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CategoryUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => CategoryUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => CategoryUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  categories?: CategoryUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  itemPrice?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => FactureUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => FactureUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => FactureUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  orders?: FactureUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  users?: UserUpdateManyWithoutProductsInput;
}

export { ProductUpdateInput as ProductUpdateInput };
